
POKEMON_CHAR_MAP = {
    0x80: "A", 0x81: "B", 0x82: "C", 0x83: "D", 0x84: "E",
    0x85: "F", 0x86: "G", 0x87: "H", 0x88: "I", 0x89: "J",
    0x8A: "K", 0x8B: "L", 0x8C: "M", 0x8D: "N", 0x8E: "O",
    0x8F: "P", 0x90: "Q", 0x91: "R", 0x92: "S", 0x93: "T",
    0x94: "U", 0x95: "V", 0x96: "W", 0x97: "X", 0x98: "Y",
    0x99: "Z", 0xA0: "a", 0xA1: "b", 0xA2: "c", 0xA3: "d",
    0xA4: "e", 0xA5: "f", 0xA6: "g", 0xA7: "h", 0xA8: "i",
    0xA9: "j", 0xAA: "k", 0xAB: "l", 0xAC: "m", 0xAD: "n",
    0xAE: "o", 0xAF: "p", 0xB0: "q", 0xB1: "r", 0xB2: "s",
    0xB3: "t", 0xB4: "u", 0xB5: "v", 0xB6: "w", 0xB7: "x",
    0xB8: "y", 0xB9: "z",
    0x7F: " ",   # space
}

POKEMON_ID_TO_NAME = {
    0x01: {"name": "Rhydon", "id": 112, "growth": "medium_fast"},
    0x02: {"name": "Kangaskhan", "id": 115, "growth": "medium_fast"},
    0x03: {"name": "Nidoran M","id": 32, "growth": "medium_fast"},
    0x04: {"name": "Clefairy","id": 35, "growth": "medium_fast"},
    0x05: {"name": "Spearow","id": 22, "growth": "medium_fast"},
    0x06: {"name": "Voltorb","id": 100, "growth": "medium_fast"},
    0x07: {"name": "Nidoking","id": 34, "growth": "medium_fast"},
    0x08: {"name": "Slowbro","id": 80, "growth": "medium_slow"},
    0x09: {"name": "Ivysaur","id": 2, "growth": "medium_fast"},
    0x0A: {"name": "Exeggutor","id": 103, "growth": "medium_fast"},
    0x0B: {"name": "Lickitung","id": 108, "growth": "medium_fast"},
    0x0C: {"name": "Exeggcute","id": 102, "growth": "medium_fast"},
    0x0D: {"name": "Grimer","id": 88, "growth": "medium_fast"},
    0x0E: {"name": "Gengar","id": 94,"growth": "medium_fast"},
    0x0F: {"name": "Nidoran F","id": 29, "growth": "medium_fast"},
    0x10: {"name": "Nidoqueen","id": 31, "growth": "medium_fast"},
    0x11: {"name": "Cubone","id": 104, "growth": "medium_slow"},
    0x12: {"name": "Rhyhorn","id": 111, "growth": "medium_fast"},
    0x13: {"name": "Lapras","id": 131, "growth": "slow"},
    0x14: {"name": "Arcanine","id": 59, "growth": "medium_fast"},
    0x15: {"name": "Mew","id": 151, "growth": "medium_fast"},
    0x16: {"name": "Gyardos","id": 130, "growth": "fast"},
    0x17: {"name": "Shellder","id": 90, "growth": "medium_fast"},
    0x18: {"name": "Tentacool","id": 72, "growth": "medium_fast"},
    0x19: {"name": "Gastly","id": 92, "growth": "fast"},
    0x1A: {"name": "Scyther","id": 123, "growth": "medium_fast"},
    0x1B: {"name": "Staryu","id": 120, "growth": "medium_fast"},
    0x1C: {"name": "Blastoise","id": 9, "growth": "medium_fast"},
    0x1D: {"name": "Pinsir","id": 127, "growth": "medium_fast"},
    0x1E: {"name": "Tangela","id": 114, "growth": "medium_fast"},
    0x21: {"name": "Growlithe","id": 58, "growth": "medium_fast"},
    0x22: {"name": "Onix","id": 95, "growth": "medium_fast"},
    0x23: {"name": "Fearow","id": 22, "growth": "medium_fast"},
    0x24: {"name": "Pidgey","id": 16, "growth": "medium_fast"},
    0x25: {"name": "Slowpoke","id": 79, "growth": "medium_slow"},
    0x26: {"name": "Kadabra","id": 64, "growth": "medium_fast"},
    0x27: {"name": "Graveler","id": 75, "growth": "medium_fast"},
    0x28: {"name": "Chansey","id": 113, "growth": "fast"},
    0x29: {"name": "Machoke","id": 67, "growth": "medium_fast"},
    0x2A: {"name": "Mr. Mime","id": 122, "growth": "medium_fast"},
    0x2B: {"name": "Hitmonlee","id": 106, "growth": "medium_fast"},
    0x2C: {"name": "Hitmonchan","id": 107, "growth": "medium_fast"},
    0x2D: {"name": "Arbok","id": 24, "growth": "medium_fast"},
    0x2E: {"name": "Parasect","id": 47, "growth": "medium_fast"},
    0x2F: {"name": "Psyduck","id": 54, "growth": "medium_fast"},
    0x30: {"name": "Drowzee","id": 102, "growth": "medium_fast"},
    0x31: {"name": "Golem","id": 76, "growth": "medium_fast"},
    0x33: {"name": "Magmar","id": 126, "growth": "medium_fast"},
    0x35: {"name": "Electabuzz","id": 125, "growth": "medium_fast"},
    0x36: {"name": "Magneton","id": 81, "growth": "medium_fast"},
    0x37: {"name": "Koffing","id": 109, "growth": "medium_fast"},
    0x39: {"name": "Mankey","id": 56, "growth": "medium_fast"},
    0x3A: {"name": "Seel","id": 87, "growth": "medium_fast"},
    0x3B: {"name": "Diglett","id": 50, "growth": "medium_fast"},
    0x3C: {"name": "Tauros","id": 128, "growth": "medium_fast"},
    0x40: {"name": "Farfetch","id": 83, "growth": "medium_fast"},
    0x41: {"name": "Venonat","id": 48, "growth": "medium_fast"},
    0x42: {"name": "Dragonite","id": 149, "growth": "fast"},
    0x46: {"name": "Doduo","id": 84, "growth": "medium_fast"},
    0x47: {"name": "Poliwag","id": 60, "growth": "medium_fast"},
    0x48: {"name": "Jynx","id": 125, "growth": "fast"},
    0x49: {"name": "Moltres","id": 146, "growth": "fast"},
    0x4A: {"name": "Articuno","id": 144, "growth": "fast"},
    0x4B: {"name": "Zapdos","id": 145, "growth": "fast"},
    0x4C: {"name": "Ditto","id": 132, "growth": "medium_fast"},
    0x4D: {"name": "Meowth","id": 52, "growth": "medium_fast"},
    0x4E: {"name": "Krabby","id": 98, "growth": "medium_fast"},
    0x52: {"name": "Vulpix","id": 37, "growth": "medium_fast"},
    0x53: {"name": "Ninetales","id": 38, "growth": "medium_fast"},
    0x54: {"name": "Pikachu","id": 25, "growth": "medium_fast"},
    0x55: {"name": "Raichu","id": 26, "growth": "medium_fast"},
    0x58: {"name": "Dratini","id": 147, "growth": "fast"},
    0x59: {"name": "Dragonair","id": 148, "growth": "fast"},
    0x5A: {"name": "Kabuto","id": 143, "growth": "medium_fast"},
    0x5B: {"name": "Kabutops","id": 144, "growth": "medium_fast"},
    0x5C: {"name": "Horsea","id": 118, "growth": "medium_fast"},
    0x5D: {"name": "Seadra","id": 119, "growth": "medium_fast"},
    0x60: {"name": "Sandshrew","id": 27, "growth": "medium_fast"},
    0x61: {"name": "Sandslash","id": 28, "growth": "medium_fast"},
    0x62: {"name": "Omanyte","id": 138, "growth": "medium_fast"},
    0x63: {"name": "Omastar","id": 139, "growth": "medium_fast"},
    0x64: {"name": "Jigglypuff","id": 39, "growth": "medium_fast"},
    0x65: {"name": "Wigglytuff","id": 40, "growth": "medium_fast"},
    0x66: {"name": "Eevee","id": 133, "growth": "medium_fast"},
    0x67: {"name": "Flareon","id": 136, "growth": "medium_fast"},
    0x68: {"name": "Jolteon","id": 135, "growth": "medium_fast"},
    0x69: {"name": "Vaporeon","id": 134, "growth": "medium_fast"},
    0x6A: {"name": "Machop","id": 66, "growth": "medium_fast"},
    0x6B: {"name": "Zubat","id": 41, "growth": "medium_fast"},
    0x6C: {"name": "Ekans","id": 23, "growth": "medium_fast"},
    0x6D: {"name": "Paras","id": 46, "growth": "medium_fast"},
    0x6E: {"name": "Poliwhirl","id": 61, "growth": "medium_fast"},
    0x6F: {"name": "Poliwrath","id": 62, "growth": "medium_fast"},
    0x70: {"name": "Weedle","id": 13, "growth": "medium_fast"},
    0x71: {"name": "Kakuna","id": 14, "growth": "medium_fast"},
    0x72: {"name": "Beedrill","id": 15, "growth": "medium_fast"},
    0x74: {"name": "Dodrio","id": 85, "growth": "medium_fast"},
    0x75: {"name": "Primeape","id": 57, "growth": "medium_fast"},
    0x76: {"name": "Dugtrio","id": 51, "growth": "medium_fast"},
    0x77: {"name": "Venomoth","id": 49, "growth": "medium_fast"},
    0x78: {"name": "Dewgong","id": 87, "growth": "medium_fast"},
    0x7B: {"name": "Caterpie","id": 10, "growth": "medium_fast"},
    0x7C: {"name": "Metapod","id": 11, "growth": "medium_fast"},
    0x7D: {"name": "Butterfree","id": 12, "growth": "medium_fast"},
    0x7E: {"name": "Machamp","id": 68, "growth": "medium_fast"},
    0x80: {"name": "Golduck","id": 54, "growth": "medium_fast"},
    0x81: {"name": "Hypno","id": 97, "growth": "medium_fast"},
    0x82: {"name": "Golbat","id": 42, "growth": "medium_fast"},
    0x83: {"name": "Mewtwo","id": 150, "growth": "slow"},
    0x84: {"name": "Snorlax","id": 143, "growth": "medium_fast"},
    0x85: {"name": "Magikarp","id": 129, "growth": "medium_fast"},
    0x88: {"name": "Muk","id": 89, "growth": "medium_fast"},
    0x8A: {"name": "Kingler","id": 99, "growth": "medium_fast"},
    0x8B: {"name": "Cloyster","id": 91, "growth": "medium_fast"},
    0x8D: {"name": "Electrode","id": 101, "growth": "medium_fast"},
    0x8E: {"name": "Clefable","id": 36, "growth": "medium_fast"},
    0x8F: {"name": "Weezing","id": 110, "growth": "medium_fast"},
    0x90: {"name": "Persian","id": 53, "growth": "medium_fast"},
    0x91: {"name": "Marowak","id": 105, "growth": "medium_slow"},
    0x93: {"name": "Haunter","id": 93, "growth": "fast"},
    0x94: {"name": "Abra","id": 63, "growth": "medium_fast"},
    0x95: {"name": "Alakazam","id": 65, "growth": "medium_fast"},
    0x96: {"name": "Pidgeotto","id": 17, "growth": "medium_fast"},
    0x97: {"name": "Pidgeot","id": 18, "growth": "medium_fast"},
    0x98: {"name": "Starmie","id": 121, "growth": "fast"},
    0x99: {"name": "Bulbasaur","id": 1, "growth": "medium_fast"},
    0x9A: {"name": "Venusaur","id": 3, "growth": "medium_fast"},
    0x9B: {"name": "Tentacruel","id": 73, "growth": "medium_fast"},
    0x9D: {"name": "Goldeen","id": 118, "growth": "medium_fast"},
    0x9E: {"name": "Seaking","id": 119, "growth": "medium_fast"},
    0xA3: {"name": "Ponyta","id": 77, "growth": "medium_fast"},
    0xA4: {"name": "Rapidash","id": 78, "growth": "medium_fast"},
    0xA5: {"name": "Rattata","id": 19, "growth": "medium_fast"},
    0xA6: {"name": "Raticate","id": 20, "growth": "medium_fast"},
    0xA7: {"name": "Nidorino","id": 33, "growth": "medium_fast"},
    0xA8: {"name": "Nidorina","id": 32, "growth": "medium_fast"},
    0xA9: {"name": "Geodude","id": 74, "growth": "medium_fast"},
    0xAA: {"name": "Porygon","id": 137, "growth": "medium_fast"},
    0xAB: {"name": "Aerodactyl","id": 142, "growth": "medium_fast"},
    0xAD: {"name": "Magnemite","id": 81, "growth": "medium_fast"},
    0xB0: {"name": "Charmander","id": 4, "growth": "medium_fast"},
    0xB1: {"name": "Squirtle","id": 7, "growth": "medium_fast"},
    0xB2: {"name": "Charmeleon","id": 5, "growth": "medium_fast"},
    0xB3: {"name": "Wartortle","id": 8, "growth": "medium_fast"},
    0xB4: {"name": "Charizard","id": 6, "growth": "medium_fast"},
    0xB9: {"name": "Oddish","id": 43, "growth": "medium_fast"},
    0xBA: {"name": "Gloom","id": 44, "growth": "medium_fast"},
    0xBB: {"name": "Vileplume","id": 45, "growth": "medium_fast"},
    0xBC: {"name": "Bellsprout","id": 69, "growth": "medium_fast"},
    0xBD: {"name": "Weepinbell","id": 70, "growth": "medium_fast"},
    0xBE: {"name": "Victreebel","id": 71, "growth": "medium_fast"},
}

POKEMON_MOVES = {
    0x01: "POUND",
    0x02: "KARATE CHOP",
    0x03: "DOUBLESLAP",
    0x04: "COMET PUNCH",
    0x05: "MEGA PUNCH",
    0x06: "PAY DAY",
    0x07: "FIRE PUNCH",
    0x08: "ICE PUNCH",
    0x09: "THUNDERPUNCH",
    0x0A: "SCRATCH",
    0x0B: "VICEGRIP",
    0x0C: "GUILLOTINE",
    0x0D: "RAZOR WIND",
    0x0E: "SWORDS DANCE",
    0x0F: "CUT",
    0x10: "GUST",
    0x11: "WING ATTACK",
    0x12: "WHIRLWIND",
    0x13: "FLY",
    0x14: "BIND",
    0x15: "SLAM",
    0x16: "VINE WHIP",
    0x17: "STOMP",
    0x18: "DOUBLE KICK",
    0x19: "MEGA KICK",
    0x1A: "JUMP KICK",
    0x1B: "ROLLING KICK",
    0x1C: "SAND-ATTACK",
    0x1D: "HEADBUTT",
    0x1E: "HORN ATTACK",
    0x1F: "FURY ATTACK",
    0x20: "HORN DRILL",
    0x21: "TACKLE",
    0x22: "BODY SLAM",
    0x23: "WRAP",
    0x24: "TAKE DOWN",
    0x25: "THRASH",
    0x26: "DOUBLE-EDGE",
    0x27: "TAIL WHIP",
    0x28: "POISON STING",
    0x29: "TWINEEDLE",
    0x2A: "PIN MISSILE",
    0x2B: "LEER",
    0x2C: "BITE",
    0x2D: "GROWL",
    0x2E: "ROAR",
    0x2F: "SING",
    0x30: "SUPERSONIC",
    0x31: "SONICBOOM",
    0x32: "DISABLE",
    0x33: "ACID",
    0x34: "EMBER",
    0x35: "FLAMETHROWER",
    0x36: "MIST",
    0x37: "WATER GUN",
    0x38: "HYDRO PUMP",
    0x39: "SURF",
    0x3A: "ICE BEAM",
    0x3B: "BLIZZARD",
    0x3C: "PSYBEAM",
    0x3D: "BUBBLEBEAM",
    0x3E: "AURORA BEAM",
    0x3F: "HYPER BEAM",
    0x40: "PECK",
    0x41: "DRILL PECK",
    0x42: "SUBMISSION",
    0x43: "LOW KICK",
    0x44: "COUNTER",
    0x45: "SEISMIC TOSS",
    0x46: "STRENGTH",
    0x47: "ABSORB",
    0x48: "MEGA DRAIN",
    0x49: "LEECH SEED",
    0x4A: "GROWTH",
    0x4B: "RAZOR LEAF",
    0x4C: "SOLARBEAM",
    0x4D: "POISONPOWDER",
    0x4E: "STUN SPORE",
    0x4F: "SLEEP POWDER",
    0x50: "PETAL DANCE",
    0x51: "STRING SHOT",
    0x52: "DRAGON RAGE",
    0x53: "FIRE SPIN",
    0x54: "THUNDERSHOCK",
    0x55: "THUNDERBOLT",
    0x56: "THUNDER WAVE",
    0x57: "THUNDER",
    0x58: "ROCK THROW",
    0x59: "EARTHQUAKE",
    0x5A: "FISSURE",
    0x5B: "DIG",
    0x5C: "TOXIC",
    0x5D: "CONFUSION",
    0x5E: "PSYCHIC",
    0x5F: "HYPNOSIS",
    0x60: "MEDITATE",
    0x61: "AGILITY",
    0x62: "QUICK ATTACK",
    0x63: "RAGE",
    0x64: "TELEPORT",
    0x65: "NIGHT SHADE",
    0x66: "MIMIC",
    0x67: "SCREECH",
    0x68: "DOUBLE TEAM",
    0x69: "RECOVER",
    0x6A: "HARDEN",
    0x6B: "MINIMIZE",
    0x6C: "SMOKESCREEN",
    0x6D: "CONFUSE RAY",
    0x6E: "WITHDRAW",
    0x6F: "DEFENSE CURL",
    0x70: "BARRIER",
    0x71: "LIGHT SCREEN",
    0x72: "HAZE",
    0x73: "REFLECT",
    0x74: "FOCUS ENERGY",
    0x75: "BIDE",
    0x76: "METRONOME",
    0x77: "MIRROR MOVE",
    0x78: "SELFDESTRUCT",
    0x79: "EGG BOMB",
    0x7A: "LICK",
    0x7B: "SMOG",
    0x7C: "SLUDGE",
    0x7D: "BONE CLUB",
    0x7E: "FIRE BLAST",
    0x7F: "WATERFALL",
    0x80: "CLAMP",
    0x81: "SWIFT",
    0x82: "SKULL BASH",
    0x83: "SPIKE CANNON",
    0x84: "CONSTRICT",
    0x85: "AMNESIA",
    0x86: "KENESIS",
    0x87: "SOFTBOILED",
    0x88: "HI JUMP KICK",
    0x89: "GLARE",
    0x8A: "DREAM EATER",
    0x8B: "POISON GAS",
    0x8C: "BARRAGE",
    0x8D: "LEECH LIFE",
    0x8E: "LOVELY KISS",
    0x8F: "SKY ATTACK",
    0x90: "TRANSFORM",
    0x91: "BUBBLE",
    0x92: "DIZZY PUNCH",
    0x93: "SPORE",
    0x94: "FLASH",
    0x95: "PSYWAVE",
    0x96: "SPLASH",
    0x97: "ACID ARMOR",
    0x98: "CRABHAMMER",
    0x99: "EXPLOSION",
    0x9A: "FURY SWIPES",
    0x9B: "BONEMERANG",
    0x9C: "REST",
    0x9D: "ROCK SLIDE",
    0x9E: "HYPER FANG",
    0x9F: "SHARPEN",
    0xA0: "CONVERSION",
    0xA1: "TRI ATTACK",
    0xA2: "SUPER FANG",
    0xA3: "SLASH",
    0xA4: "SUBSTITUTE",
    0xA5: "STRUGGLE",
}

MAP_NAMES = {
    0: "Pallet Town",
    1: "Viridian City",
    2: "Pewter City",
    3: "Cerulean City",
    4: "Lavender Town",
    5: "Vermilion City",
    6: "Celadon City",
    7: "Fuchsia City",
    8: "Cinnabar Island",
    9: "Pokémon League",
    10: "Saffron City",
    11: "Unused Fly location",
    12: "Route 1",
    13: "Route 2",
    14: "Route 3",
    15: "Route 4",
    16: "Route 5",
    17: "Route 6",
    18: "Route 7",
    19: "Route 8",
    20: "Route 9",
    21: "Route 10",
    22: "Route 11",
    23: "Route 12",
    24: "Route 13",
    25: "Route 14",
    26: "Route 15",
    27: "Route 16",
    28: "Route 17",
    29: "Route 18",
    30: "Sea Route 19",
    31: "Sea Route 20",
    32: "Sea Route 21",
    33: "Route 22",
    34: "Route 23",
    35: "Route 24",
    36: "Route 25",
    37: "Red's house (first floor)",
    38: "Red's house (second floor)",
    39: "Blue's house",
    40: "Professor Oak's Lab",
    41: "Pokémon Center (Viridian City)",
    42: "Poké Mart (Viridian City",
    43: "School (Viridian City",
    44: "House 1 (Viridian City",
    45: "Gym (Viridian City)",
    46: "Diglett's Cave (Route 2 entrance)",
    47: "Gate (Viridian City/Pewter City) (Route 2)",
    48: "Oak's Aide House 1 (Route 2)",
    49: "Gate (Route 2)",
    50: "Gate (Route 2/Viridian Forest) (Route 2)",
    51: "Viridian Forest",
    52: "Pewter Museum (floor 1)",
    53: "Pewter Museum (floor 2)",
    54: "Gym (Pewter City)",
    55: "House with disobedient Nidoran♂ (Pewter City)",
    56: "Poké Mart (Pewter City)",
    57: "House with two Trainers (Pewter City)",
    58: "Pokémon Center (Pewter City)",
    59: "Mt. Moon (Route 3 entrance)",
    60: "Mt. Moon",
    61: "Mt. Moon",
    62: "Invaded house (Cerulean City",
    63: "Poliwhirl for Jynx trade house (Red/Bl",
    64: "Pokémon Center (Cerulean City)",
    65: "Gym (Cerulean City)",
    66: "Bike Shop (Cerulean City)",
    67: "Poké Mart (Cerulean City)",
    68: "Pokémon Center (Route 4)",
    69: "Invaded house - alternative music (Cerulean City",
    70: "Saffron City Gate (Route 5)",
    71: "Entrance to Underground Path (Route 5)",
    72: "Daycare Center (Route 5)",
    73: "Saffron City Gate (Route 6)",
    74: "Entrance to Underground Path (Route 6)",
    75: "Entrance to Underground Path (alternative music) (Route 6)",
    76: "Saffron City Gate (Route 7)",
    77: "Entrance to Underground Path (Route 7)",
    78: "Entrance to Underground Path (unused) (Route 7)",
    79: "Saffron City Gate (Route 8)",
    80: "Entrance to Underground Path (Route 8)",
    81: "Pokémon Center (Rock Tunnel)",
    82: "Rock Tunnel",
    83: "Power Plan",
    84: "Gate 1F (Route 11-Route 12)",
    85: "Diglett's Cave (Vermilion City entrance",
    86: "Gate 2F (Route 11-Route 12)",
    87: "Gate (Route 12-Route 13)",
    88: "Sea Cottag",
    89: "Pokémon Center (Vermilion City)",
    90: "Pokémon Fan Club (Vermilion City)",
    91: "Poké Mart (Vermilion City)",
    92: "Gym (Vermilion City)",
    93: "House with Pidgey (Vermilion City)",
    94: "Vermilion Harbor (Vermilion City",
    95: "S.S. Anne 1F",
    96: "S.S. Anne 2F",
    97: "S.S. Anne 3F",
    98: "S.S. Anne B1F",
    99: "S.S. Anne (Deck)",
    100: "S.S. Anne (Kitchen)",
    101: "S.S. Anne (Captain's room)",
    102: "S.S. Anne 1F (Gentleman's room)",
    103: "S.S. Anne 2F (Gentleman's room)",
    104: "S.S. Anne B1F (Sailor/Fisherman's room)",
    105: "Unused (Victory Road)",
    106: "Unused (Victory Road)",
    107: "Unused (Victory Road)",
    108: "Victory Road (Route 23 entrance)",
    109: "Unused (Pokémon League)",
    110: "Unused (Pokémon League)",
    111: "Unused (Pokémon League)",
    112: "Unused (Pokémon League)",
    113: "Lance's Elite Four room",
    114: "Unused (Pokémon League)",
    115: "Unused (Pokémon League)",
    116: "Unused (Pokémon League)",
    117: "Unused (Pokémon League)",
    118: "Hall of Fame",
    119: "Underground Path (Route 5-Route 6)",
    120: "Blue (Champion)'s room",
    121: "Underground Path (Route 7-Route 8)",
    122: "Celadon Department Store 1F	18 (RB)	11 ",
    123: "Celadon Department Store 2F",
    124: "Celadon Department Store 3F",
    125: "Celadon Department Store 4F",
    126: "Celadon Department Store Rooftop Square",
    127: "Celadon Department Store Lift",
    128: "Celadon Mansion 1F",
    129: "Celadon Mansion 2F",
    130: "Celadon Mansion 3F",
    131: "Celadon Mansion 4F",
    132: "Celadon Mansion 4F (Eevee building)",
    133: "Pokémon Center (Celadon City)",
    134: "Gym (Celadon City)",
    135: "Rocket Game Corner (Celadon City)",
    136: "Celadon Department Store 5F",
    137: "Prize corner (Celadon City)",
    138: "Restaurant (Celadon City)",
    139: "House with Team Rocket members (Celadon City)",
    140: "Hotel (Celadon City)",
    141: "Pokémon Center (Lavender Town)",
    142: "Pokémon Tower 1F",
    143: "Pokémon Tower 2F",
    144: "Pokémon Tower 3F",
    145: "Pokémon Tower 4F",
    146: "Pokémon Tower 5F",
    147: "Pokémon Tower 6F",
    148: "Pokémon Tower 7F",
    149: "Mr. Fuji's house (Lavender Town)",
    150: "Poké Mart (Lavender Town)",
    151: "House with NPC discussing Cubone's mother",
    152: "Poké Mart (Fuchsia City)",
    153: "House with NPCs discussing Bill (Fuchsia City)",
    154: "Pokémon Center (Fuchsia City)",
    155: "Warden's house (Fuchsia City)",
    156: "Safari Zone gate (Fuchsia City)",
    157: "Gym (Fuchsia City)",
    158: "House with NPCs discussing Baoba (Fuchsia City)",
    159: "Seafoam Islands",
    160: "Seafoam Islands",
    161: "Seafoam Islands",
    162: "Seafoam Islands",
    163: "Vermilion City Fishing Brother",
    164: "Fuchsia City Fishing Brother",
    165: "Pokémon Mansion (1F)",
    166: "Gym (Cinnabar Island)",
    167: "Pokémon Lab (Cinnabar Island)",
    168: "Pokémon Lab - Trade room (Cinnabar Island)",
    169: "Pokémon Lab - Room with scientists (Cinnabar Island)",
    170: "Pokémon Lab - Fossil resurrection room (Cinnabar Island)",
    171: "Pokémon Center (Cinnabar Island)",
    172: "Poké Mart (Cinnabar Island)",
    173: "Poké Mart - alternative music (Cinnabar Island)",
    174: "Pokémon Center (Indigo Plateau",
    175: "Copycat's house 1F (Saffron City)",
    176: "Copycat's house 2F (Saffron City)",
    177: "Fighting Dojo (Saffron City)",
    178: "Gym (Saffron City)",
    179: "House with Pidgey (Saffron City",
    180: "Poké Mart (Saffron City)",
    181: "Silph Co. 1F",
    182: "Pokémon Center (Saffron City)",
    183: "Mr. Psychic's house (Saffron City",
    184: "Gate 1F (Route 15)",
    185: "Gate 2F (Route 15)",
    186: "Gate 1F (Cycling Road) (Route 16)",
    187: "Gate 2F (Cycling Road) (Route 16)",
    188: "Secret house (Cycling Road) (Route 16",
    189: "Route 12 Fishing Brother",
    190: "Gate 1F (Route 18)",
    191: "Gate 2F (Route 18)",
    192: "Seafoam Islands",
    193: "Badges check gate (Route 22",
    194: "Victory Road",
    195: "Gate 2F (Route 12)",
    196: "House with NPC and HM moves advice (Vermilion City)",
    197: "Diglett's Cave",
    198: "Victory Road",
    199: "Team Rocket Hideout (B1F)",
    200: "Team Rocket Hideout (B2F)",
    201: "Team Rocket Hideout (B3F)",
    202: "Team Rocket Hideout (B4F)",
    203: "Team Rocket Hideout (Lift)",
    204: "Unused (Team Rocket Hideout)",
    205: "Unused (Team Rocket Hideout)",
    206: "Unused (Team Rocket Hideout)",
    207: "Silph Co. (2F)",
    208: "Silph Co. (3F)",
    209: "Silph Co. (4F)",
    210: "Silph Co. (5F)",
    211: "Silph Co. (6F)",
    212: "Silph Co. (7F)",
    213: "Silph Co. (8F)",
    214: "Pokémon Mansion (2F)",
    215: "Pokémon Mansion (3F)",
    216: "Pokémon Mansion (B1F)",
    217: "Safari Zone (Area 1)",
    218: "Safari Zone (Area 2)",
    219: "Safari Zone (Area 3)",
    220: "Safari Zone (Entrance)",
    221: "Safari Zone (Rest house 1)",
    222: "Safari Zone (Prize house)",
    223: "Safari Zone (Rest house 2)",
    224: "Safari Zone (Rest house 3)",
    225: "Safari Zone (Rest house 4)",
    226: "Cerulean Cave",
    227: "Cerulean Cave 1F",
    228: "Cerulean Cave B1F",
    229: "Name Rater's house (Lavender Town",
    230: "Cerulean City (Gym Badge man)",
    231: "Unused (Rock Tunnel)",
    232: "Rock Tunnel",
    233: "Silph Co. 9F",
    234: "Silph Co. 10F",
    235: "Silph Co. 11F",
    236: "Silph Co. Lift",
    239: "Cable Club Trade Center(*)",
    240: "Cable Club Colosseum(*)",
    245: "Lorelei's room",
    246: "Bruno's room",
    247: "Agatha's room",
    248: "Summer Beach House",
    255: "Indoor-Outside Map Hand"
}